package com.leetcode;

import com.eclipsesource.json.JsonArray;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * @Author: Aaron Yang
 * @Date: 10/13/2018 10:35 AM
 */
public class FindTheDifference {

    public static String stringToString(String input) {
        return JsonArray.readFrom("[" + input + "]").get(0).asString();
    }

    public static String charToString(char c) {
        return stringToString(String.valueOf(c));
    }

    public static void main(String[] args) throws IOException {
        BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
        String line;
        while ((line = in.readLine()) != null) {
            String s = stringToString(line);
            line = in.readLine();
            String t = stringToString(line);

            char ret = new Solution68().findTheDifference(s, t);

            String out = charToString(ret);

            System.out.print(out);
        }
    }
}

class Solution68 {
    public char findTheDifference(String s, String t) {
        int[] map = new int[26];
        if (s.length() > t.length()) {
            for (int i = 0; i < t.length(); i++) {
                map[t.toCharArray()[i] - 'a']++;
                map[s.toCharArray()[i] - 'a']++;
            }
            map[s.toCharArray()[s.length() - 1] - 'a']++;
        } else {
            for (int i = 0; i < s.length(); i++) {
                map[t.toCharArray()[i] - 'a']++;
                map[s.toCharArray()[i] - 'a']++;
            }
            map[t.toCharArray()[t.length() - 1] - 'a']++;
        }

        for (int i = 0; i < map.length; i++) {
            if (map[i] % 2 != 0) return (char) (i + 'a');
        }
        return ' ';
    }
}
